---
title: "Linear Modeling"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("ggplot2")
library(ggplot2)
```

##This R Markdown Uses Linear Modeling to Find Phenotypes That Have Sex and Diet Effects and Sex-Diet Interaction Effects

Load in the phenotype data
```{r cars}
setwd("~/Projects/DO/data")
file=list.files(pattern="clean")
data=read.csv(file, header=T)[,-1:-3]
#turn all data into numeric
for(i in 7:ncol(data)){
  data[,i]=as.numeric(as.character(data[,i]))
  }
#Look at data
summary(data)[,1:10]
```

##Model the Diet and Sex Effects with lm
```{r lm}
#make empty lists
mod.sexdiet=vector("list")
mod.sexXdiet=vector("list")
mod.sex=vector("list")
mod.diet=vector("list")
mod.null=vector("list")

#do linear regression with phenotype against covariates
for(i in 7:ncol(data)){
  mod.sexdiet[[names(data)[i]]]=lm(data[,i]~data$Sex+data$Diet+data$Gen, data=data)
  mod.sexXdiet[[names(data)[i]]]=lm(data[,i]~Sex*Diet+Gen, data=data)
  mod.sex[[names(data)[i]]]=lm(data[,i]~data$Sex+data$Gen, data=data)
  mod.diet[[names(data)[i]]]=lm(data[,i]~data$Diet+data$Gen, data=data)
  mod.null[[names(data)[i]]]=lm(data[,i]~data$Gen, data=data)
}
```

##ANOVA for lm Comparison
Use ANOVA test to find the best linear model for each phenotype
```{r anova}
#make empty data frames
p.sex=data.frame()
p.diet=data.frame()
p.int=data.frame()

#add anova pvals into data frames
for(nm in names(mod.sex)){
  p.sex=rbind(p.sex, anova(mod.sexdiet[[nm]], mod.diet[[nm]])[2,6])
  p.diet=rbind(p.diet, anova(mod.sexdiet[[nm]], mod.sex[[nm]])[2,6])
  p.int=rbind(p.int, anova(mod.sexdiet[[nm]], mod.sexXdiet[[nm]])[2,6])
}
#combine into 1 giant data frame
pval=data.frame(p.sex,p.diet, p.int)
rownames(pval)=names(mod.sex)
names(pval)=c('p.sex','p.diet','p.int')

#look at the result (p.sex, p.diet, and p.int are P-vals obtained from ANOVA, an a value <0.05 means that the phenotype is significantly affected by the corresponding factor )
head(pval)
#uncomment to export as a CSV
#write.csv(pval, file="../results/6-15-16/pval.csv")
```

##Find the Significant P-Values
```{r significance}
#subset pval dataframe to get only significant ones as export as csv
#sex
num=which(pval[,1]<0.05)
pval.sex.sig=matrix(pval[num,1])
rownames(pval.sex.sig)=rownames(pval)[num]
colnames(pval.sex.sig)=colnames(pval)[1]
#write.csv(pval.sex.sig, file="../results/6-15-16/pval_sex_sig.csv")
#peek
head(pval.sex.sig)

#diet
num=which(pval[,2]<0.05)
pval.diet.sig=matrix(pval[num,2])
rownames(pval.diet.sig)=rownames(pval)[num]
colnames(pval.diet.sig)=colnames(pval)[2]
#write.csv(pval.diet.sig, file="../results/6-15-16/pval_diet_sig.csv")
#peek
head(pval.diet.sig)

#sex and diet interacting
num=which(pval[,3]<0.05)
pval.int.sig=matrix(pval[num,3])
rownames(pval.int.sig)=rownames(pval)[num]
colnames(pval.int.sig)=colnames(pval)[3]
#write.csv(pval.int.sig, file="../results/6-15-16/pval_int_sig.csv")
#peek
head(pval.int.sig)

#find the mininum pval for each phenotype
for(i in 1:3){
  num=c(num,which(pval[,i]<0.05))
}
uni=unique(num)
pval.sig=pval[uni,]
indx=vector()
min=vector()
for (i  in 1:nrow(pval.sig)){
  indx[i]=which.min(as.numeric(pval.sig[i,]))
  min[i]=min(as.numeric(pval.sig[i,]))
  
}
indx=gsub("1", "p.sex", x=indx)
indx=gsub("2", "p.diet", x=indx)
indx=gsub("3", "p.int", x=indx)

#make a dataframe with phenotype, which covar, and the p-value
lowest=data.frame(phenotypes=rownames(pval.sig), which=indx, pval=min)

#peek
head(lowest)
#export as csv
#write.csv(lowest, file="../results/6-15-16/pval_min.csv")
```

#Visualize what this means
The pretty stuff
```{r the pretty stuff, warning=FALSE}
#plot a phenotype with significant sex-diet interaction
tail(pval.int.sig)
#See how the lines cross? That means that Sex and Diet are interacting with each other in this phenotype
ggplot(data, aes(x=Sex, y=data$WBC2, group=Diet, col=Diet))+
    geom_jitter(width=0.3)+
    geom_smooth()+
    theme_classic()+
    labs(y="WBC2") +
    ggtitle("WBC2 interactions")

```

